### ISSUE TITLE
Translation of mdb files to sqlite using Python

### ISSUE THREAD

**Issue by PardeeCenterIFs** [PardeeCenterDU/IFs-Issues-Tracking#145]
1. Python is not translating a few characters in the names of fields when I convert ifs.mdb to ifs.db, using script: mdb2sqliteNone.py. For example in table: PovRateAgeBothSexes: 0-4 is translated 0_4, and All ages is translated as All_ages, is this something we can handle in python? I suppose is just the “-“ and “ “ that are problematic, at least that’s what I’ve found so far.

I found another character that is not getting translated, “+”, for example in table GBDDeaths, field 80+, gets translated as 80_

2. Can I ask for something else in that script, only for the case where we are translating ifs.mdb, table Currency, it’s getting translated fine, but my code has problems understanding a Byte datatype, so I have been manually converting the last field “Currency Flag” from Byte into Integer, and updating all False to be 0, and the one True to be 1, could we add that code to the script, so that it automatically does it when converting ifs.mdb.

**Comment by quciet** [comment]
A quick question José @solox1, are you using SQLiteStudio to open and explore SQLite data? If so, what version are you using?

**Comment by PardeeCenterIFs** [comment]
Hi Yutang, no I'm not using SQLiteStudio, I use: 

DB Browser for SQLite Version 3.12.2

**Comment by quciet** [comment]
@solox1  Hey there, the 1st issue has been fixed, I'm working on the 2nd issue now. SQLite itself does not support boolean data type, per their website, 
**SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true).
SQLite recognizes the keywords "TRUE" and "FALSE", as of version 3.23.0 (2018-04-02) but those keywords are really just alternative spellings for the integer literals 1 and 0 respectively**
And I know the DataDict table has many Yes/No columns. So I suggest we change all the BIT type columns from MS Acess to INTEGER columns in SQLite. 

Let me know what you think.

**Comment by PardeeCenterIFs** [comment]
I think that's a great idea Yutang, please go ahead and translate all booleans/bit type columns from MS Access to INTEGER columns in SQLite.

**Comment by quciet** [comment]
I'm just putting some reminders here. Currently, we are working on the following things,

1. Replace SQLite with SQLcipher to encrypt databases, e.g., IFsHistSeries
2. Some tables need customization-
There are 3 tables where we use the field name “Number” and our .NET code doesn’t like it. Let's rename those to RegionId.
PopAgeSingleRegionFemale
PopAgeSingleRegionMale
PopFertilityCohortRegionFemale
3. Only convert Yes/No to 0/1 when the original field is designed to be a boolean type. For example, country code for Norway in ISO2 is "NO".

**Comment by PardeeCenterIFs** [comment]
Hi Yutang, I'm having problems with text fields that have "Yes" or "No", and are being translated to "1" ot "0", for example in DataDict.mdb. I think this is probably the same issue you have label in your previous message, item 3.

**Comment by quciet** [comment]
> Hi Yutang, I'm having problems with text fields that have "Yes" or "No", and are being translated to "1" ot "0", for example in DataDict.mdb. I think this is probably the same issue you have label in your previous message, item 3.

Both issue 2 & 3 should be fixed now. Note that there might be more tables that have Number field, and they all will be converted to "RegionId"

**Comment by PardeeCenterIFs** [comment]
This issue was completed by Yutang (mdb2sqlite.py)

**Comment by PardeeCenterIFs** [comment]
Hi Yutang,

Today I tried converting the bilateral files in: https://ifs02.du.edu/BilateralInteractionData/DyadicHistSeriesAndDataDict%2020220704%20Ver%207.84%20or%20newer.zip

I got a message saying it was skipping the big ifsHistSeriesDyadic.mdb, maybe it's because of the links to external tables (FBIC).

**Comment by quciet** [comment]
> 

That might be the case. Since we are using SQLite, the space limitation won't be a problem anymore. We will need to combine two files into 1. 

How urgent is this, I can make some ad hoc changes.

**Comment by solox1** [comment]
Hi Yutang,

This is top priority for me, right after those poverty tables we were
talking about earlier today.

**Comment by quciet** [comment]
Hi there,

I found the issue, and unfortunately, I do not have an elegant way to solve it. The solution requires some manual changes-

1. I updated the code to recognize linked tables, so please use the updated script attached. 
[mdb2sqlite.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/10036519/mdb2sqlite.zip)

2. However, to make sure the script works, you need to ensure those tables are properly linked. For example, since our dyadic tables are linked using an absolute path instead of a relative path, whenever you move the files, you will need to relink the tables. When I was testing, I opened up **SeriesBandwith** table in the **IFsHistSeriesDyadic.mdb** file and this happened, 
![image](https://user-images.githubusercontent.com/34465524/202581755-20380272-ea57-41ad-832a-becd02318262.png)
Then I had to go through the linked table manager,
![image](https://user-images.githubusercontent.com/34465524/202581887-eb0874a3-e602-492c-80f4-199f33120570.png)
and redirect (relink) Access to find the correct path of the table that is being linked to, 
![image](https://user-images.githubusercontent.com/34465524/202581951-2289de5f-4f38-4b3d-b018-d31f231e381b.png)
Once that is succeeded, the script can run normally.

3. Another downside is that the script is basically converting those linked tables twice which takes much more time. Hence, you can see that from my test run, both **IFsHistSeriesDyadic.mdb** and **IFsHistSeriesDyadic_FBIC.mdb** were converted into actual SQL files. You will then need to manually delete **IFsHistSeriesDyadic_FBIC.db** since all those values under linked tables are already stored into **IFsHistSeriesDyadic.db**
![image](https://user-images.githubusercontent.com/34465524/202582358-e843acc3-f56d-417b-874b-657f099b1cab.png)

**Comment by PardeeCenterIFs** [comment]
That all makes sense, and I don't think it's a problem, but I'm still getting an error when running it, could you help me check if I'm doing something wrong:

![image](https://user-images.githubusercontent.com/33665510/202727314-dca99bd8-6cd0-452c-8fb2-c7eefa328f3d.png)

I'm trying this is the old server, which I think you have access too: DESKTOP-LJ2QQ78

Here is the path, after running the script the access file seems corrupted, for now I have reseted it and re-link, so it's ready for you to run the script.

G:\Python\DyadicHistSeriesAndDataDict 20220704 Ver 7.84 or newer

**Comment by PardeeCenterIFs** [comment]
This task was completed on March 23rd, ready to use in version 7.95 .NET.
